server:
  port: 8000
  servlet:
    context-path: /
spring:
  application:
    name: application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: DbPassword
    url: jdbc:mysql://47.108.180.43:3306/jyf?characterEncoding=utf-8&serverTimezone=GMT%2B8
logging:
  path: logs
  config: classpath:logback-base.xml

swagger:
  enable: true
